'use strict';

module.exports = {
    up: (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('links', [{
                name: 'Explore new positions',
                linkTarget: 'http://localhost:4200/careers',
                iconLink: 'icon link value',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'action',
            }, {
                name: 'Find us',
                linkTarget: 'http://localhost:4200/contacts',
                iconLink: 'icon link value2',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'action',
            },
            {
                name: 'facebook',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-facebook',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'twitter',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-twitter',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'skype',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-skype',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'slack',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-slack',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'google-plus',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-google-plus',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'linkedin',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-linkedin',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'instagram',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-instagram',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'firefox',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-firefox',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            },
            {
                name: 'github',
                linkTarget: 'https://www.facebook.com/TelerikAcademy/',
                iconLink: 'fa fa-github',
                hidden: null,
                createdAt: new Date(),
                updatedAt: new Date(),
                type: 'social',
            }
        ], {});
    },
};